application: proyecto-als
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: handlers.main.app

- url: /inicio
  script: handlers.inicio.app
  login: required

- url: /chats/nuevo
  script: handlers.chats.nuevo.app
  login: required

- url: /chats/elimina
  script: handlers.chats.elimina.app
  login: required

- url: /mensajes/elimina
  script: handlers.mensajes.elimina.app
  login: required

- url: /mensajes/lista
  script: handlers.mensajes.lista.app
  login: required

- url: /mensajes/nuevo
  script: handlers.mensajes.nuevo.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "latest"
